export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


//PRODUCT
export const SAVE_PRODUCT_SUCCESS ='SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE'

export const GET_ALL_PRODUCTS_SUCCESS ='GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE ='GET_ALL_PRODUCTS_FAILURE'

export const GET_SINGLE_PRODUCTS_SUCCESS='GET_SINGLE_PRODUCTS_SUCCESS'
export const GET_SINGLE_PRODUCTS_FAILURE='GET_SINGLE_PRODUCTS_FAILURE'

export const DELETE_SINGLE_PRODUCTS_SUCCESS='DELETE_SINGLE_PRODUCTS_SUCCESS'
export const DELETE_SINGLE_PRODUCTS_FAILURE='DELETE_SINGLE_PRODUCTS_FAILURE'

export const UPDATE_SINGLE_PRODUCTS_SUCCESS='UPDATE_SINGLE_PRODUCTS_SUCCESS'
export const UPDATE_SINGLE_PRODUCTS_FAILURE='UPDATE_SINGLE_PRODUCTS_FAILURE'

export const LOADING_DATA='LOADING_DATA'
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA'


//CLIENT
export const SAVE_CLIENT_SUCCESS ='SAVE_CLIENT_SUCCESS'
export const SAVE_CLIENT_FAILURE = 'SAVE_CLIENT_FAILURE'

export const GET_ALL_CLIENTS_SUCCESS ='GET_ALL_CLIENTS_SUCCESS'
export const GET_ALL_CLIENTS_FAILURE ='GET_ALL_CLIENTS_FAILURE'

export const GET_SINGLE_CLIENTS_SUCCESS='GET_SINGLE_CLIENTS_SUCCESS'
export const GET_SINGLE_CLIENTS_FAILURE='GET_SINGLE_CLIENTS_FAILURE'

export const DELETE_SINGLE_CLIENTS_SUCCESS='DELETE_SINGLE_CLIENTS_SUCCESS'
export const DELETE_SINGLE_CLIENTS_FAILURE='DELETE_SINGLE_CLIENTS_FAILURE'

export const UPDATE_SINGLE_CLIENTS_SUCCESS='UPDATE_SINGLE_CLIENTS_SUCCESS'
export const UPDATE_SINGLE_CLIENTS_FAILURE='UPDATE_SINGLE_CLIENTS_FAILURE'

export const CLEAR_ALL_CLIENT_DATA='CLEAR_ALL_CLIENT_DATA'
export const LOADING_CLIENT_DATA='LOADING_CLIENT_DATA'






//CLIENT SIDE OPERATION

export const LOGIN_CLIENT_SUCCESS='LOGIN_CLIENT_SUCCESS'
export const LOGIN_CLIENT_FAILURE='LOGIN_CLIENT_FAILURE'
export const LOGOUT_CLIENT_ACTIONTYPE='LOGOUT_CLIENT_ACTIONTYPE'
export const UPDATE_CLIENT_PRODUCT_PREFERENCE='UPDATE_CLIENT_PRODUCT_PREFERENCE'
export const UPDATE_CLIENT_DETAILS='UPDATE_CLIENT_DETAILS'







